import * as fs from 'fs';
import * as path from 'path';
import {execSync} from 'child_process';

/**
 * Locate a binary inside the project's own `node_modules/.bin`, walking up from
 * `cwd` so hoisted / monorepo layouts resolve too. Returns null when the project
 * doesn't provide it (i.e. only a global install would be found on PATH).
 */
const findProjectBin = (bin: string, cwd: string): {exe: string; binDir: string} | null => {
    const name = process.platform === 'win32' ? `${bin}.cmd` : bin;
    let dir = path.resolve(cwd);
    // eslint-disable-next-line no-constant-condition
    while (true) {
        const binDir = path.join(dir, 'node_modules', '.bin');
        const exe = path.join(binDir, name);
        if (fs.existsSync(exe)) return {exe, binDir};
        const parent = path.dirname(dir);
        if (parent === dir) return null;
        dir = parent;
    }
};

/**
 * Run a project-local CLI binary (e.g. `prisma`) from the PROJECT's node_modules.
 *
 * The `appx-core` CLI is normally installed **globally**, so the project's
 * `node_modules/.bin` is not on PATH — a bare `prisma generate` would resolve to
 * a global Prisma (a different version than the project's, or nothing at all).
 * We resolve the executable inside the project and prepend its `.bin` to PATH so
 * that anything the tool spawns — Prisma's generator binaries such as
 * `prisma-nestjs-graphql` — also resolves from the project.
 *
 * Throws with an actionable message rather than silently falling back to a
 * global install, since generating against the wrong Prisma version is exactly
 * the failure this avoids.
 */
export const runProjectBin = (bin: string, args: string, cwd: string = process.cwd()): void => {
    const found = findProjectBin(bin, cwd);
    if (!found) {
        throw new Error(
            `Could not find "${bin}" in this project's node_modules. ` +
            `Run "npm install" in the project root and try again.`,
        );
    }
    execSync(`"${found.exe}" ${args}`.trim(), {
        cwd,
        stdio: 'inherit',
        env: {...process.env, PATH: `${found.binDir}${path.delimiter}${process.env.PATH ?? ''}`},
    });
};

export const kebabToPascalCase = (str: string) => {
    return str
        .split("-")
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
        .join("");
};

export const pascalToKebabCase = (str: string) => {
    return str
        .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
        .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
        .toLowerCase();
};

/**
 * The HTTP route prefix for a model's generated controller: the kebab-case model
 * name plus a plural 's'.
 *
 *   AlbumMember     → album-members
 *   PublishSettings → publish-settings   (already ends in 's' — not doubled)
 *   Tenant          → tenants
 *
 * Kebab-case so the route matches the file names this generator emits
 * (`album-member.controller.ts`) instead of running the words together.
 *
 * Deliberately NOT a pluralization engine — no English -ies/-es rules, since
 * model names here are not necessarily English. The only guard is against
 * emitting a doubled 's'.
 */
export const modelRoutePath = (name: string): string => {
    const kebab = pascalToKebabCase(name);
    return kebab.endsWith('s') ? kebab : `${kebab}s`;
};

export const createFileIfNotExists = (filePath: string, content: string) => {
    console.log(`Creating ${filePath}...`);
    if (!fs.existsSync(filePath)) {
        fs.mkdirSync(path.dirname(filePath), {recursive: true});
        fs.writeFileSync(filePath, content);
        console.log(`${filePath} created.`);
    } else {
        console.log(`${filePath} already exists, skipping.`);
    }
};

/**
 * Banner stamped on every fully-generated file. These files live under
 * `src/generated/` (gitignored) and are OVERWRITTEN on every `appx generate`.
 * Never hand-edit them — customize the hand-owned subclass under
 * `src/modules/<model>/dto/` instead.
 */
export const GENERATED_BANNER =
    '// @Generated by appx-core — do not edit.\n' +
    '// Regenerated by `appx generate`; lives under src/generated (gitignored).\n' +
    '// To customize, edit the hand-owned subclass in src/modules/<model>/dto.\n';

/**
 * Writes a fully-generated file, always overwriting. Use only for artifacts
 * under `src/generated/` that carry {@link GENERATED_BANNER}. Creates parent
 * directories as needed.
 */
export const writeGeneratedFile = (filePath: string, content: string) => {
    fs.mkdirSync(path.dirname(filePath), {recursive: true});
    fs.writeFileSync(filePath, content);
    console.log(`Generated ${filePath}`);
};

/**
 * Framework-owned models. Excluded from model discovery: no generic CRUD module,
 * controller, service, resolver, or DTO is scaffolded for them. `Session` /
 * `UserRefreshToken` are framework plumbing; `User` is owned by the auth module
 * (generic User CRUD would be a mass-assignment surface, and `/auth/*` already
 * covers user endpoints), so it is hidden from the module wizard entirely.
 */
export const FRAMEWORK_MODELS = ['Session', 'UserRefreshToken', 'User'];

/**
 * The kebab-case folder / file basename for a model. Matches the folder naming
 * of the prisma-nestjs-graphql generator output under `src/generated/`, so the
 * scaffolded resolver's imports (`../../generated/<folder>/<folder>.model`)
 * resolve. E.g. `ProjectMember` -> `project-member`, `TypeSample` -> `type-sample`.
 */
export const modelFolder = (modelName: string): string => pascalToKebabCase(modelName);

/**
 * Loads the datamodel from the consumer project's generated Prisma client and
 * returns the discoverable (non-framework-owned) models. This is the single
 * source of truth for "what models exist" — independent of whatever folders the
 * GraphQL plugin happened to emit. Requires `@prisma/client` lazily so callers
 * can run `prisma generate` first and pick up a fresh schema in the same process.
 */
export const loadAllModels = (): any[] => {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const {Prisma} = require(path.join(process.cwd(), 'node_modules', '@prisma/client'));
    return Prisma.dmmf.datamodel.models as any[];
};

export const loadModels = (): any[] => loadAllModels().filter((m) => !FRAMEWORK_MODELS.includes(m.name));

/** True if a module exists at the model's canonical folder under src/modules. */
export const moduleExists = (modelName: string): boolean => {
    const folder = modelFolder(modelName);
    return fs.existsSync(path.join(process.cwd(), 'src/modules', folder, `${folder}.module.ts`));
};

/**
 * The set of model names already served by existing module source — detected by
 * the `CoreController<Model>` / `CoreService<Model>` type argument. Pure (takes
 * file contents) so it is unit-testable. This catches a module that serves a
 * model under a NON-canonical folder name (e.g. a hand-written pluralised
 * `wearable-connections/` module owning the `WearableConnection` model), which a
 * folder-name check (`moduleExists`) would miss — preventing the wizard from
 * scaffolding a duplicate module + controller on a second route.
 */
export const modelsServedBySource = (contents: string[]): Set<string> => {
    const owned = new Set<string>();
    const re = /Core(?:Controller|Service)<\s*([A-Za-z0-9_]+)\s*>/g;
    for (const content of contents) {
        let m: RegExpExecArray | null;
        while ((m = re.exec(content)) !== null) owned.add(m[1]);
    }
    return owned;
};

/** Scans src/modules for the models already served by an existing module. */
export const ownedModels = (): Set<string> => {
    const root = path.join(process.cwd(), 'src/modules');
    if (!fs.existsSync(root)) return new Set();
    const contents: string[] = [];
    for (const dir of fs.readdirSync(root)) {
        const dirPath = path.join(root, dir);
        if (!fs.statSync(dirPath).isDirectory()) continue;
        for (const file of fs.readdirSync(dirPath)) {
            if (file.endsWith('.ts')) contents.push(fs.readFileSync(path.join(dirPath, file), 'utf8'));
        }
    }
    return modelsServedBySource(contents);
};