import * as fs from 'fs';
import * as path from 'path';

export const kebabToPascalCase = (str: string) => {
    return str
        .split("-")
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
        .join("");
};

export const pascalToKebabCase = (str: string) => {
    return str
        .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
        .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
        .toLowerCase();
};

export const createFileIfNotExists = (filePath: string, content: string) => {
    console.log(`Creating ${filePath}...`);
    if (!fs.existsSync(filePath)) {
        fs.mkdirSync(path.dirname(filePath), {recursive: true});
        fs.writeFileSync(filePath, content);
        console.log(`${filePath} created.`);
    } else {
        console.log(`${filePath} already exists, skipping.`);
    }
};

/**
 * Banner stamped on every fully-generated file. These files live under
 * `src/generated/` (gitignored) and are OVERWRITTEN on every `appx generate`.
 * Never hand-edit them — customize the hand-owned subclass under
 * `src/modules/<model>/dto/` instead.
 */
export const GENERATED_BANNER =
    '// @Generated by appx-core — do not edit.\n' +
    '// Regenerated by `appx generate`; lives under src/generated (gitignored).\n' +
    '// To customize, edit the hand-owned subclass in src/modules/<model>/dto.\n';

/**
 * Writes a fully-generated file, always overwriting. Use only for artifacts
 * under `src/generated/` that carry {@link GENERATED_BANNER}. Creates parent
 * directories as needed.
 */
export const writeGeneratedFile = (filePath: string, content: string) => {
    fs.mkdirSync(path.dirname(filePath), {recursive: true});
    fs.writeFileSync(filePath, content);
    console.log(`Generated ${filePath}`);
};

export const IGNORE_FOLDERS = [
    'prisma',
    'schema.gql',
    'session',
    'user-refresh-token',
    // Generated DTOs live under src/generated/dto/. The model generators scan
    // src/generated's top-level dirs as model names, so this must be skipped or
    // they emit a bogus `dto` module.
    'dto',
];