/**
 * §5 of ROADMAP.md — `appx-core create` ↔ committed fixture parity.
 *
 * Approach:
 *   1. Drive `node cli/cli.js create` non-interactively (piped stdin) against
 *      a clean `appx_parity` database on the testcontainer.
 *   2. Compare the produced project tree against `test/fixtures/scaffold-app/`.
 *   3. Normalize known per-run differences (random secrets, dependency ref,
 *      generated migrations, .git, node_modules, dist) and assert the rest
 *      matches exactly.
 *
 * If the test fails on whitespace / quote-style / trailing-comma differences
 * that look like prettier reformatting, that's the surfaced finding —
 * cli.js runs `prettier --write .` post-scaffold, but build-fixture.mjs
 * doesn't. Either run prettier on the fixture (in build-fixture.mjs) or
 * normalize via prettier in this test.
 *
 * Skipped (returns early) if:
 *   - APPX_PARITY_CREDS env var is missing (APPX_SKIP_FIXTURE=1 was set).
 *   - The CLI subprocess fails to complete in time (npm install / network).
 */
import { spawn, execSync } from 'child_process';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const CLI_PATH = path.join(REPO_ROOT, 'cli', 'cli.js');
const FIXTURE_DIR = path.join(REPO_ROOT, 'test', 'fixtures', 'scaffold-app');
const PROJECT_NAME = 'scaffold-app';

/** Paths under either tree that we deliberately ignore in the diff. */
const SKIP_PREFIXES = [
    'node_modules/',
    'dist/',
    '.git/',
    'prisma/migrations/',         // cli.js runs migrate dev; fixture doesn't have a migrations dir
    'src/generated/',             // emitted by prisma-nestjs-graphql; gitignored in fixture
    'src/modules/',               // emitted by appx-core generate; gitignored in fixture
];
const SKIP_EXACT = new Set([
    // Per-run / install artifacts
    '.env',                       // contains random secrets per run
    '.env.development',           // written by globalSetup with live container creds
    '.env.test',
    '.env.example',               // fixture-only convention; cli.js doesn't emit this
    'package-lock.json',          // npm install artifact, varies per resolver run
    'src/app.module.ts',          // regenerated by globalSetup; gitignored in fixture

    // Fixture diverges from raw scaffold by design — enrichments for runtime tests
    'prisma/schema.prisma',                  // fixture adds Tenant/Project/etc.
    'src/config/permissions.config.ts',      // fixture has richer ABAC config
    'src/config/admin.config.ts',            // fixture exposes more AdminJS resources

    // Hand-written by build-fixture.mjs (not from @nestjs/cli/schematics)
    'tsconfig.json',
    'tsconfig.build.json',
    '.gitignore',                            // fixture has appx-specific extra entries
    'package.json',                          // dep is file:.. + simpler shape
]);

function shouldSkip(rel: string): boolean {
    if (SKIP_EXACT.has(rel)) return true;
    return SKIP_PREFIXES.some((p) => rel === p.replace(/\/$/, '') || rel.startsWith(p));
}

function walk(root: string, base = root): Map<string, string> {
    const out = new Map<string, string>();
    if (!fs.existsSync(root)) return out;
    for (const entry of fs.readdirSync(root, { withFileTypes: true })) {
        const full = path.join(root, entry.name);
        const rel = path.relative(base, full).replace(/\\/g, '/');
        if (shouldSkip(rel)) continue;
        if (entry.isDirectory()) {
            for (const [k, v] of walk(full, base)) out.set(k, v);
        } else {
            try { out.set(rel, fs.readFileSync(full, 'utf8')); }
            catch { /* binary or unreadable — skip */ }
        }
    }
    return out;
}

/**
 * Reformat every prettier-compatible file in `dir` via prettier installed
 * as our devDep. prettier v3 is ESM and can't be require()d in jest's CJS
 * VM, so we invoke its bin directly via absolute path. One subprocess per
 * directory tree.
 */
const PRETTIER_BIN = path.resolve(REPO_ROOT, 'node_modules', '.bin', 'prettier');
function normalizeTreeViaPrettier(dir: string): void {
    execSync(
        `"${PRETTIER_BIN}" --write "**/*.{ts,tsx,js,jsx,json,yml,yaml,md}" --log-level=error`,
        { cwd: dir, stdio: ['ignore', 'ignore', 'inherit'] },
    );
}

/**
 * Per-file substitutions for things prettier can't normalize: secrets,
 * dependency refs that differ by intent. Applied AFTER prettier so the
 * substitution targets the canonical post-prettier shape.
 */
function normalize(rel: string, content: string): string {
    let c = content;
    if (rel === '.env.example' || rel === '.env') {
        c = c
            .replace(/^(SESSION_SECRET=).*$/m, '$1<NORMALIZED>')
            .replace(/^(JWT_SECRET=).*$/m, '$1<NORMALIZED>')
            .replace(/^(JWT_REFRESH_SECRET=).*$/m, '$1<NORMALIZED>')
            .replace(/^(SESSION_COOKIE_NAME=).*$/m, '$1<NORMALIZED>');
    }
    if (rel === 'package.json') {
        try {
            const pkg = JSON.parse(c);
            if (pkg.dependencies?.['@appxdigital/appx-core']) {
                pkg.dependencies['@appxdigital/appx-core'] = '<NORMALIZED>';
            }
            c = JSON.stringify(pkg, null, 2) + '\n';
        } catch { /* leave as-is */ }
    }
    c = c.replace(/\r\n/g, '\n').replace(/[ \t]+$/gm, '');
    if (!c.endsWith('\n')) c += '\n';
    return c;
}

describe('§5 — cli/cli.js create produces the committed fixture (parity)', () => {
    const credsRaw = process.env.APPX_PARITY_CREDS;
    // The parity check validates scaffold-template output, which is
    // provider-independent (the datasource `provider` line is normalized out of
    // the comparison). Run it once, on mysql: the dbProvider list prompt does
    // not reliably accept piped input without a TTY, so driving a postgres
    // scaffold this way is unreliable and adds no coverage.
    const isMysql = (process.env.DB_PROVIDER || 'mysql').toLowerCase().startsWith('mysql');
    const itOrSkip = credsRaw && isMysql ? test : test.skip;

    itOrSkip('produces the same scaffold-template output as build-fixture.mjs', async () => {
        const creds = JSON.parse(credsRaw!);
        const tmpdir = fs.mkdtempSync(path.join(os.tmpdir(), 'appx-parity-'));

        // Spawn cli.js create. Drive prompts by writing all answers up-front
        // into stdin. inquirer reads line-by-line for input/confirm/password
        // prompts. The list prompt (dbProvider) is the risk — without a TTY
        // it may not accept the typed answer cleanly. We send the literal
        // string anyway; on failure, document and fall back to a less
        // ambitious test.
        // Isolate the subprocess from the parent's DB environment. cli.js runs
        // `prisma migrate dev`, and Prisma prioritizes a DATABASE_URL present in
        // the environment over the project's own .env. If the parent's
        // DATABASE_URL (appx_proxy / appx_fixture — set by globalSetup and other
        // specs) leaked in, migrate dev would RESET that shared database and
        // break other suites. Strip them so the scaffold's generated .env
        // (pointing at the isolated appx_parity) is authoritative.
        const childEnv: NodeJS.ProcessEnv = { ...process.env, FORCE_COLOR: '0', CI: '1' };
        // Disable CLI self-update: the subprocess must not hit the registry or
        // trigger a real global `npm install -g` during the parity run.
        childEnv.APPX_CORE_NO_AUTO_UPDATE = '1';
        delete childEnv.DATABASE_URL;
        delete childEnv.APPX_PROXY_DB_URL;
        delete childEnv.APPX_FIXTURE_DB_URL;
        delete childEnv.APPX_PARITY_DB_URL;

        const proc = spawn('node', [CLI_PATH, 'create'], {
            cwd: tmpdir,
            stdio: ['pipe', 'pipe', 'pipe'],
            env: childEnv,
        });

        let stdout = '';
        let stderr = '';
        proc.stdout!.on('data', (d) => { stdout += d.toString(); });
        proc.stderr!.on('data', (d) => { stderr += d.toString(); });

        // Order of prompts in cli/cli.js (see promptUser):
        //   1. projectName  (input)
        //   2. dbProvider   (list — default first option "mysql")
        //   3. dbHost       (input)
        //   4. dbPort       (input)
        //   5. dbUser       (input)
        //   6. dbPassword   (password)
        //   7. dbName       (input)
        //   8. showOutput   (confirm)
        //   9. configureFileUpload (confirm)
        const dbProviderAnswer = creds.provider === 'postgresql' ? 'postgresql' : '';
        const answers = [
            PROJECT_NAME,
            dbProviderAnswer,
            creds.host, creds.port, creds.user, creds.password, creds.dbName,
            'y',  // showOutput=yes (avoids the progress bar fighting our stdout)
            'n',  // configureFileUpload=no
        ];

        // Don't close stdin — inquirer treats EOF as "user cancelled" and aborts
        // with ExitPromptError. Write answers with small delays so each prompt
        // has time to render before the next answer is consumed.
        const exited = new Promise<number>((resolve) => proc.on('close', (c) => resolve(c ?? -1)));

        // Initial wait for inquirer to render the first prompt.
        await new Promise((r) => setTimeout(r, 800));
        for (const a of answers) {
            if (proc.exitCode !== null) break;       // already done / crashed
            proc.stdin.write(a + '\n');
            await new Promise((r) => setTimeout(r, 400));
        }

        const code = await exited;

        // eslint-disable-next-line no-console
        console.log(`[parity] cli.js create exited ${code}; tmpdir=${tmpdir}`);
        // eslint-disable-next-line no-console
        console.log(`[parity] stdout (last 2KB):\n${stdout.slice(-2000)}`);
        // eslint-disable-next-line no-console
        console.log(`[parity] stderr (last 2KB):\n${stderr.slice(-2000)}`);
        // eslint-disable-next-line no-console
        console.log(`[parity] tmpdir contents: ${fs.readdirSync(tmpdir).join(', ')}`);

        if (code !== 0) {
            throw new Error(`cli.js create exited ${code} — see logs above`);
        }

        // 2. Locate produced project. cli.js puts it in cwd if cwd is empty,
        //    else in cwd/<projectName>. Tmpdir starts empty, so the project
        //    ends up directly in tmpdir.
        const producedSubdir = path.join(tmpdir, PROJECT_NAME);
        const producedRoot = fs.existsSync(path.join(producedSubdir, 'package.json'))
            ? producedSubdir
            : tmpdir;
        if (!fs.existsSync(path.join(producedRoot, 'package.json'))) {
            throw new Error(
                `cli.js create did not produce a project. Looked in ${producedSubdir} and ${tmpdir}. ` +
                `Contents: ${JSON.stringify(fs.readdirSync(tmpdir))}`,
            );
        }

        // 3. Normalize both halves via pinned prettier. cli.js's `npx --yes
        //    prettier` and build-fixture.mjs's `npx --yes prettier` resolve
        //    different versions over time → different array-wrapping decisions.
        //    Re-running with a pinned version makes the comparison meaningful:
        //    any remaining diff is real scaffold content drift.
        const fixtureCopyDir = fs.mkdtempSync(path.join(os.tmpdir(), 'appx-parity-fixture-'));
        fs.cpSync(FIXTURE_DIR, fixtureCopyDir, {
            recursive: true,
            filter: (src) => {
                const rel = path.relative(FIXTURE_DIR, src).replace(/\\/g, '/');
                if (!rel) return true;
                // Don't copy gigantic dirs into the prettier-norm tmp
                return !rel.startsWith('node_modules') && !rel.startsWith('dist')
                    && !rel.startsWith('src/generated') && !rel.startsWith('src/modules');
            },
        });

        // eslint-disable-next-line no-console
        console.log('[parity] normalizing both trees through prettier@3.8.3…');
        normalizeTreeViaPrettier(producedRoot);
        normalizeTreeViaPrettier(fixtureCopyDir);

        const produced = walk(producedRoot);
        const fixture = walk(fixtureCopyDir);

        // 3. Compare file sets (post-skip).
        const producedKeys = new Set(produced.keys());
        const fixtureKeys = new Set(fixture.keys());

        const onlyInProduced: string[] = [];
        const onlyInFixture: string[] = [];
        for (const k of producedKeys) if (!fixtureKeys.has(k)) onlyInProduced.push(k);
        for (const k of fixtureKeys) if (!producedKeys.has(k)) onlyInFixture.push(k);

        const fileSetDiff: string[] = [];
        if (onlyInProduced.length) fileSetDiff.push(`Only in created: ${onlyInProduced.join(', ')}`);
        if (onlyInFixture.length) fileSetDiff.push(`Only in fixture: ${onlyInFixture.join(', ')}`);
        expect(fileSetDiff).toEqual([]);

        // 5. Compare contents file-by-file (after per-file substitution).
        const contentMismatches: string[] = [];
        for (const k of producedKeys) {
            const a = normalize(k, produced.get(k)!);
            const b = normalize(k, fixture.get(k)!);
            if (a !== b) {
                contentMismatches.push(k);
            }
        }

        if (contentMismatches.length > 0) {
            const k = contentMismatches[0];
            const a = normalize(k, produced.get(k)!);
            const b = normalize(k, fixture.get(k)!);
            // eslint-disable-next-line no-console
            console.error(
                `\n[parity] First content mismatch in ${k}:\n` +
                `--- created (${a.length} bytes) ---\n${a}\n` +
                `--- fixture (${b.length} bytes) ---\n${b}\n`,
            );
        }
        expect(contentMismatches).toEqual([]);
    }, 5 * 60_000);    // 5 min — npm install dominates
});
