/**
 * Real-fixture counterpart to test/cli/generate.spec.ts (which uses
 * synthesized tmpdirs).
 *
 * The synthesized suite is a fast unit-style template regression — it can run
 * with no DB or Prisma involvement. This suite asserts the same invariants
 * against the actually-generated output in test/fixtures/scaffold-app/, which
 * has been produced by jest's globalSetup via the full pipeline:
 *
 *   prisma db push  →  prisma generate  →  prisma-nestjs-graphql  →
 *   appx-core generate (generate-modules, -resolvers, -services, -controllers)
 *   →  tsc -p tsconfig.build.json
 *
 * Together the two layers verify both shape (synthesized) and end-to-end
 * pipeline integrity (this file). They cover different failure modes — keep
 * both.
 */
import * as fs from 'fs';
import * as path from 'path';

const SCAFFOLD = path.resolve(__dirname, '..', 'fixtures', 'scaffold-app');

describe('appx-core generate — real fixture output (end-to-end)', () => {
    test('User module directory + four canonical files exist after globalSetup', () => {
        const userDir = path.join(SCAFFOLD, 'src', 'modules', 'user');
        expect(fs.existsSync(userDir)).toBe(true);
        for (const f of ['user.module.ts', 'user.controller.ts', 'user.service.ts', 'user.resolver.ts']) {
            expect(fs.existsSync(path.join(userDir, f))).toBe(true);
        }
    });

    test('user.controller.ts wires CoreController<User> with the right entity name and route', () => {
        const c = fs.readFileSync(path.join(SCAFFOLD, 'src/modules/user/user.controller.ts'), 'utf8');
        expect(c).toMatch(/@Controller\('users'\)/);
        expect(c).toMatch(/extends CoreController<User>/);
        expect(c).toMatch(/static get entityName\(\):\s*string\s*\{[\s\S]*return\s*'User'/);
    });

    test('(fixed 0.1.124) — generator emits DTOs and the controller types its body with them', () => {
        // The fix: the generator emits a class-validator DTO per model+action.
        // Base (overwritten, gitignored) under src/generated/dto/<model>/; a
        // hand-owned subclass under src/modules/<model>/dto/; the controller
        // overrides create/update with the concrete DTO type so ValidationPipe
        // can whitelist unknown fields.
        const baseCreate = path.join(SCAFFOLD, 'src/generated/dto/user/create-user.generated.dto.ts');
        const subCreate = path.join(SCAFFOLD, 'src/modules/user/dto/create-user.dto.ts');
        expect(fs.existsSync(baseCreate)).toBe(true);
        expect(fs.existsSync(subCreate)).toBe(true);

        // Base carries the @Generated banner and real class-validator decorators.
        const base = fs.readFileSync(baseCreate, 'utf8');
        expect(base).toMatch(/@Generated by appx-core/);
        expect(base).toMatch(/class-validator/);
        // password is @Role(none) → excluded; id is @id → excluded.
        expect(base).not.toMatch(/\bpassword\b/);
        expect(base).not.toMatch(/^\s*id[?!]:/m);

        const c = fs.readFileSync(path.join(SCAFFOLD, 'src/modules/user/user.controller.ts'), 'utf8');
        expect(c).toMatch(/CreateUserDto/);
        expect(c).toMatch(/UpdateUserDto/);
    });

    test('user.service.ts calls super(prisma.model.user) — first char lowercased', () => {
        const s = fs.readFileSync(path.join(SCAFFOLD, 'src/modules/user/user.service.ts'), 'utf8');
        expect(s).toMatch(/super\(prisma\.model\.user\)/);
        expect(s).toMatch(/class UserService extends CoreService<User>/);
    });

    test('user.module.ts wires controller + service + resolver via PrismaModule', () => {
        const m = fs.readFileSync(path.join(SCAFFOLD, 'src/modules/user/user.module.ts'), 'utf8');
        expect(m).toMatch(/PrismaModule/);
        expect(m).toMatch(/controllers:\s*\[UserController\]/);
        expect(m).toMatch(/providers:\s*\[UserService,\s*UserResolver\]/);
    });

    test('app.module.ts has UserModule added by updateAppModule', () => {
        const am = fs.readFileSync(path.join(SCAFFOLD, 'src/app.module.ts'), 'utf8');
        expect(am).toMatch(/import\s*\{\s*UserModule\s*\}\s*from\s*'\.\/modules\/user\/user\.module'/);
        expect(am).toMatch(/imports:\s*\[[^\]]*UserModule/);
    });

    test('src/generated/user/ exists and has prisma-nestjs-graphql output', () => {
        const generated = path.join(SCAFFOLD, 'src', 'generated', 'user');
        expect(fs.existsSync(generated)).toBe(true);
        const files = fs.readdirSync(generated);
        // prisma-nestjs-graphql emits at least one .ts per model
        expect(files.filter((f) => f.endsWith('.ts')).length).toBeGreaterThan(0);
    });

    test('fixture compiles cleanly (proves generator output is type-correct)', () => {
        // buildFixtureApp() in globalSetup ran `tsc -p tsconfig.build.json` and
        // would have thrown on any type error. dist/ existing is the artefact.
        expect(fs.existsSync(path.join(SCAFFOLD, 'dist', 'modules', 'user', 'user.module.js'))).toBe(true);
        expect(fs.existsSync(path.join(SCAFFOLD, 'dist', 'app.module.js'))).toBe(true);
    });

    test('(regression) — generate-modules skips files when the schema only declares directories', () => {
        // After globalSetup, src/modules/ should only contain folders, never
        // stray files (the workaround in globalSetup strips .gitkeep before
        // generate). If a future change accidentally writes a file here, the
        // next generate run would inject a broken import into app.module.ts.
        const modulesDir = path.join(SCAFFOLD, 'src', 'modules');
        for (const entry of fs.readdirSync(modulesDir, { withFileTypes: true })) {
            expect(entry.isDirectory()).toBe(true);
        }
    });
});
