/**
 * Real-fixture counterpart to test/cli/generate.spec.ts (which uses
 * synthesized tmpdirs).
 *
 * The synthesized suite is a fast unit-style template regression — it can run
 * with no DB or Prisma involvement. This suite asserts the same invariants
 * against the actually-generated output in test/fixtures/scaffold-app/, which
 * has been produced by jest's globalSetup via the full pipeline:
 *
 *   prisma db push  →  prisma generate  →  prisma-nestjs-graphql  →
 *   appx-core generate (generate-modules, -resolvers, -services, -controllers)
 *   →  tsc -p tsconfig.build.json
 *
 * Together the two layers verify both shape (synthesized) and end-to-end
 * pipeline integrity (this file). They cover different failure modes — keep
 * both.
 */
import * as fs from 'fs';
import * as path from 'path';

const SCAFFOLD = path.resolve(__dirname, '..', 'fixtures', 'scaffold-app');

describe('appx-core generate — real fixture output (end-to-end)', () => {
    // The example model for the structural/field-policy assertions is TypeSample —
    // a plain domain model with no relations that carries one writable field per
    // scalar type plus non-writable fields (`secret` @Role(none), `internalNote`
    // @NoWrite). (User is framework-owned and no longer scaffolded, so it isn't a
    // generatable module.)
    test('TypeSample module directory + three canonical files exist after globalSetup', () => {
        // GraphQL is now opt-in per module (add CoreGraphqlResolver to providers),
        // so no per-module resolver file is scaffolded anymore.
        const dir = path.join(SCAFFOLD, 'src', 'modules', 'type-sample');
        expect(fs.existsSync(dir)).toBe(true);
        for (const f of ['type-sample.module.ts', 'type-sample.controller.ts', 'type-sample.service.ts']) {
            expect(fs.existsSync(path.join(dir, f))).toBe(true);
        }
        expect(fs.existsSync(path.join(dir, 'type-sample.resolver.ts'))).toBe(false);
    });

    test('type-sample.controller.ts wires CoreController<TypeSample> with the right entity name and route', () => {
        const c = fs.readFileSync(path.join(SCAFFOLD, 'src/modules/type-sample/type-sample.controller.ts'), 'utf8');
        expect(c).toMatch(/@Controller\('type-samples'\)/);
        expect(c).toMatch(/extends CoreController<TypeSample>/);
        expect(c).toMatch(/static get entityName\(\):\s*string\s*\{[\s\S]*return\s*'TypeSample'/);
    });

    test('generator emits DTOs and the controller types its body with them', () => {
        // The generator emits a class-validator DTO per model+action. Base
        // (overwritten, gitignored) under src/generated/dto/<model>/; a hand-owned
        // subclass under src/modules/<model>/dto/; the controller overrides
        // create/update with the concrete DTO type so ValidationPipe can whitelist
        // unknown fields.
        const baseCreate = path.join(SCAFFOLD, 'src/generated/dto/type-sample/create-type-sample.generated.dto.ts');
        const subCreate = path.join(SCAFFOLD, 'src/modules/type-sample/dto/create-type-sample.dto.ts');
        expect(fs.existsSync(baseCreate)).toBe(true);
        expect(fs.existsSync(subCreate)).toBe(true);

        // Base carries the @Generated banner and real class-validator decorators.
        const base = fs.readFileSync(baseCreate, 'utf8');
        expect(base).toMatch(/@Generated by appx-core/);
        expect(base).toMatch(/class-validator/);
        // secret is @Role(none) and internalNote is @NoWrite → both excluded; id
        // is @id → excluded from the entity's own writable fields.
        expect(base).not.toMatch(/\bsecret\b/);
        expect(base).not.toMatch(/\binternalNote\b/);
        const mainClass = base.slice(base.indexOf('export class CreateTypeSampleGeneratedDto'));
        expect(mainClass).not.toMatch(/^\s*id[?!]:/m);

        const c = fs.readFileSync(path.join(SCAFFOLD, 'src/modules/type-sample/type-sample.controller.ts'), 'utf8');
        expect(c).toMatch(/CreateTypeSampleDto/);
        expect(c).toMatch(/UpdateTypeSampleDto/);
    });

    test('scalar columns are typed to match the Prisma model (Date / Decimal / bigint)', () => {
        const base = fs.readFileSync(
            path.join(SCAFFOLD, 'src/generated/dto/type-sample/update-type-sample.generated.dto.ts'),
            'utf8',
        );
        // DateTime → Date via @Type(() => Date).
        expect(base).toMatch(/@Type\(\(\) => Date\)\s*\n\s*@IsDate\(\)\s*\n\s*dueAt\?: Date;/);
        // Decimal → Prisma.Decimal via @DecimalField().
        expect(base).toMatch(/@DecimalField\(\)\s*\n\s*amount\?: Prisma\.Decimal;/);
        // BigInt → bigint via @BigIntField().
        expect(base).toMatch(/@BigIntField\(\)\s*\n\s*big\?: bigint;/);
        // The framework + Prisma type imports are emitted.
        expect(base).toMatch(/import \{ BigIntField, DecimalField \} from '@appxdigital\/appx-core';/);
        expect(base).toMatch(/import \{[^}]*\bPrisma\b[^}]*\} from '@prisma\/client';/);
    });

    test('create DTO emits the nested-write allowlist (create/connect only) for relations', () => {
        const base = fs.readFileSync(
            path.join(SCAFFOLD, 'src/generated/dto/project/create-project.generated.dto.ts'),
            'utf8',
        );
        // Parent create DTO exposes relations, typed to nested-write DTOs.
        const parent = base.slice(base.indexOf('export class CreateProjectGeneratedDto'));
        expect(parent).toMatch(/tasks\?: ProjectTasksNestedWriteDto;/);
        expect(parent).toMatch(/tags\?: ProjectTagsNestedWriteDto;/);
        // Nested-write DTOs expose ONLY create/connect — no other operator.
        const write = base.slice(
            base.indexOf('export class ProjectTasksNestedWriteDto'),
            base.indexOf('export class CreateProjectGeneratedDto'),
        );
        expect(write).toMatch(/create\?:/);
        expect(write).toMatch(/connect\?:/);
        expect(write).not.toMatch(/\b(set|disconnect|update|upsert|delete|deleteMany|createMany|connectOrCreate)\?:/);
        // The back-reference FK is omitted from a nested create (parent sets it).
        const nestedCreate = base.slice(
            base.indexOf('export class ProjectTasksCreateNestedDto'),
            base.indexOf('export class ProjectTasksConnectNestedDto'),
        );
        expect(nestedCreate).not.toMatch(/\bprojectId\b/);
        // update DTOs stay scalar-only (updateMany can't carry nested writes).
        const upd = fs.readFileSync(
            path.join(SCAFFOLD, 'src/generated/dto/project/update-project.generated.dto.ts'),
            'utf8',
        );
        expect(upd).not.toMatch(/NestedWriteDto/);
    });

    test('type-sample.service.ts calls super(prisma.model.typeSample) — first char lowercased', () => {
        const s = fs.readFileSync(path.join(SCAFFOLD, 'src/modules/type-sample/type-sample.service.ts'), 'utf8');
        expect(s).toMatch(/super\(prisma\.model\.typeSample\)/);
        expect(s).toMatch(/class TypeSampleService extends CoreService<TypeSample>/);
    });

    test('type-sample.module.ts wires controller + service via PrismaModule, with a commented GraphQL opt-in', () => {
        const m = fs.readFileSync(path.join(SCAFFOLD, 'src/modules/type-sample/type-sample.module.ts'), 'utf8');
        expect(m).toMatch(/PrismaModule/);
        expect(m).toMatch(/controllers:\s*\[TypeSampleController\]/);
        // Service is a real provider; the GraphQL resolver is present only as a
        // commented, copy-paste-ready opt-in line (no resolver registered by default).
        expect(m).toMatch(/providers:\s*\[\s*TypeSampleService,/);
        expect(m).toMatch(/\/\/\s*CoreGraphqlResolver\(TypeSampleGraphql\),/);
        expect(m).not.toMatch(/^\s*TypeSampleResolver\b/m);
    });

    test('deploy-safe pass emits a GraphQL bundle (src/generated/type-sample/graphql.ts)', () => {
        const bundle = path.join(SCAFFOLD, 'src/generated/type-sample/graphql.ts');
        expect(fs.existsSync(bundle)).toBe(true);
        const b = fs.readFileSync(bundle, 'utf8');
        expect(b).toMatch(/export const TypeSampleGraphql/);
        expect(b).toMatch(/model:\s*TypeSample/);
        expect(b).toMatch(/findManyArgs:\s*FindManyTypeSampleArgs/);
        expect(b).toMatch(/findFirstArgs:\s*FindFirstTypeSampleArgs/);
    });

    test('app.module.ts has TypeSampleModule added by the module wizard', () => {
        const am = fs.readFileSync(path.join(SCAFFOLD, 'src/app.module.ts'), 'utf8');
        expect(am).toMatch(/import\s*\{\s*TypeSampleModule\s*\}\s*from\s*'\.\/modules\/type-sample\/type-sample\.module'/);
        expect(am).toMatch(/imports:\s*\[[^\]]*TypeSampleModule/);
    });

    test('User is framework-owned — no generated User CRUD module', () => {
        // User is excluded from discovery (auth owns user endpoints; generic User
        // CRUD is a mass-assignment surface), so the wizard never scaffolds it.
        expect(fs.existsSync(path.join(SCAFFOLD, 'src', 'modules', 'user'))).toBe(false);
        const am = fs.readFileSync(path.join(SCAFFOLD, 'src/app.module.ts'), 'utf8');
        expect(am).not.toMatch(/UserModule\s*\}\s*from\s*'\.\/modules\/user/);
    });

    test('src/generated/type-sample/ exists and has prisma-nestjs-graphql output', () => {
        const generated = path.join(SCAFFOLD, 'src', 'generated', 'type-sample');
        expect(fs.existsSync(generated)).toBe(true);
        const files = fs.readdirSync(generated);
        // prisma-nestjs-graphql emits at least one .ts per model
        expect(files.filter((f) => f.endsWith('.ts')).length).toBeGreaterThan(0);
    });

    test('fixture compiles cleanly (proves generator output is type-correct)', () => {
        // buildFixtureApp() in globalSetup ran `tsc -p tsconfig.build.json` and
        // would have thrown on any type error. dist/ existing is the artefact.
        expect(fs.existsSync(path.join(SCAFFOLD, 'dist', 'modules', 'type-sample', 'type-sample.module.js'))).toBe(true);
        expect(fs.existsSync(path.join(SCAFFOLD, 'dist', 'app.module.js'))).toBe(true);
    });

    test('(regression) — generate-modules skips files when the schema only declares directories', () => {
        // After globalSetup, src/modules/ should only contain folders, never
        // stray files (the workaround in globalSetup strips .gitkeep before
        // generate). If a future change accidentally writes a file here, the
        // next generate run would inject a broken import into app.module.ts.
        const modulesDir = path.join(SCAFFOLD, 'src', 'modules');
        for (const entry of fs.readdirSync(modulesDir, { withFileTypes: true })) {
            expect(entry.isDirectory()).toBe(true);
        }
    });
});
